module.exports={
google:{
  clientID:'630529680176-rn3pdv58r6s2rh8v7fm9khobv50p994i.apps.googleusercontent.com',
  clientSecret:'dkU8YLfceCzCP9PcDUZDDOKv'
},
  mongodb:{
     dbURI:'mongodb+srv://abhi:abhi123@clusterabhi-zzvfm.mongodb.net/test?retryWrites=true&w=majority'
},
  session:{
      cookieKey:'projectpassport'
  }
};